name = "emby-keepalive"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "emby-keepalive"
database_id = "ee121f46-9432-4a6f-87b3-68c406c318c7"
